# Generated by Django 3.2.12 on 2022-03-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0008_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='recieved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='recieved_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
