# Generated by Django 3.2.12 on 2022-03-15 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0010_historicalstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalstock',
            old_name='last_updated',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='last_updated',
            new_name='date',
        ),
    ]
