# Generated by Django 3.2.12 on 2022-03-22 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0011_auto_20220315_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
