# Generated by Django 3.2.12 on 2022-03-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0012_auto_20220322_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='timestamp',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
