# Generated by Django 3.2.12 on 2022-03-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0013_auto_20220322_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
