# Generated by Django 3.2.12 on 2022-03-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0014_alter_stock_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='timestamp',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Date format: 01-02-2025'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='timestamp',
            field=models.DateField(auto_now=True, null=True, verbose_name='Date format: 01-02-2025'),
        ),
    ]
