# Generated by Django 3.2.12 on 2022-03-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0015_auto_20220324_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstock',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date format: 01-01-2030'),
        ),
        migrations.AddField(
            model_name='historicalstock',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date format: 01-01-2030'),
        ),
        migrations.AddField(
            model_name='stock',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date format: 01-01-2030'),
        ),
        migrations.AddField(
            model_name='stock',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date format: 01-01-2030'),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='timestamp',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='timestamp',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
