# Generated by Django 3.2.12 on 2022-05-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0016_auto_20220324_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='To Date (yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='From Date (yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='To Date (yyyy-mm-dd)'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='From Date (yyyy-mm-dd)'),
        ),
    ]
