# Generated by Django 4.0.4 on 2022-05-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0017_auto_20220509_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalstock',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical stock', 'verbose_name_plural': 'historical stocks'},
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
