# Generated by Django 4.0.4 on 2022-05-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0019_alter_historicalstock_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
