# Generated by Django 4.0.4 on 2022-05-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0021_alter_historicalstock_issue_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='issue_quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='recieve_quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='historicalstock',
            name='reorder_level',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='issue_quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='recieve_quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='reorder_level',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
