# Generated by Django 4.0.4 on 2022-05-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0023_remove_historicalstock_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstock',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalstock',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='To Date (yyyy-mm-dd)'),
        ),
        migrations.AddField(
            model_name='historicalstock',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='From Date (yyyy-mm-dd)'),
        ),
        migrations.AddField(
            model_name='historicalstock',
            name='timestamp',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='To Date (yyyy-mm-dd)'),
        ),
        migrations.AddField(
            model_name='stock',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='From Date (yyyy-mm-dd)'),
        ),
        migrations.AddField(
            model_name='stock',
            name='timestamp',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
