# Generated by Django 4.0.4 on 2022-07-03 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockmgmt', '0024_historicalstock_date_historicalstock_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('amount', models.IntegerField(blank=True, default='0', null=True)),
                ('purpose', models.CharField(blank=True, max_length=150, null=True)),
                ('timestamp', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='historicalstock',
            name='net_sales',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='historicalstock',
            name='total_expenses',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='historicalstock',
            name='total_sales',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='net_sales',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='total_expenses',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='total_sales',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.CreateModel(
            name='HistoricalExpenses',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('amount', models.IntegerField(blank=True, default='0', null=True)),
                ('purpose', models.CharField(blank=True, max_length=150, null=True)),
                ('timestamp', models.DateField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical expenses',
                'verbose_name_plural': 'historical expensess',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
