# Generated by Django 4.0.4 on 2022-07-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0026_historicalstock_expense_stock_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstock',
            name='price',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
