# Generated by Django 4.0.6 on 2023-02-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0028_pos_historicalpos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=1000)),
                ('sender', models.CharField(max_length=11)),
                ('mobile', models.CharField(max_length=2000)),
            ],
        ),
    ]
