# Generated by Django 4.0.6 on 2023-02-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0029_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sms',
            name='mobile',
            field=models.TextField(max_length=2000),
        ),
    ]
