# Generated by Django 4.0.6 on 2023-02-14 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0030_alter_sms_message_alter_sms_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms',
            old_name='mobile',
            new_name='mobiles',
        ),
        migrations.RenameField(
            model_name='sms',
            old_name='pwd',
            new_name='password',
        ),
    ]
