# Generated by Django 4.0.6 on 2023-02-22 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0032_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstock',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stockmgmt.member'),
        ),
        migrations.AddField(
            model_name='stock',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.member'),
        ),
    ]
