# Generated by Django 4.0.6 on 2023-02-22 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0033_historicalstock_member_stock_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstock',
            name='member',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stockmgmt.member'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.member'),
        ),
    ]
